import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x79c9f5);scene.fog=new THREE.Fog(0x79c9f5,140,360);
const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,500);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.getElementById('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdff7ff,0x31532d,2));const sun=new THREE.DirectionalLight(0xffefc4,3.2);sun.position.set(-80,130,70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const world=new THREE.Group();scene.add(world);const locations=[];const roadMeshes=[];
const mat=(c,e=0,r=.7)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:.15,emissive:e,emissiveIntensity:e?1.4:0});
function mesh(g,m,x,y,z){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;world.add(o);return o}
function box(w,h,d,c,x,y,z,e=0){return mesh(new THREE.BoxGeometry(w,h,d),mat(c,e),x,y,z)}
function cyl(r,h,c,x,y,z,e=0){return mesh(new THREE.CylinderGeometry(r,r,h,24),mat(c,e),x,y,z)}
// ocean + island
box(430,2,430,0x147da1,0,-3,0);const island=cyl(150,2,0x2e8a54,0,-1.2,0);island.scale.z=.86;
// beaches
for(let i=0;i<90;i++){const a=Math.random()*Math.PI*2,r=118+Math.random()*24,x=Math.cos(a)*r,z=Math.sin(a)*r*.86;cyl(.8+Math.random()*1.6,.25,0xdcc27a,x,.15,z)}
// mountain backdrop
for(let i=0;i<24;i++){const a=Math.random()*Math.PI*2,r=165+Math.random()*30,h=20+Math.random()*35;const x=Math.cos(a)*r;const z=Math.sin(a)*r*.86;const m=mesh(new THREE.ConeGeometry(12+Math.random()*10,h,6),mat(0x5c7f86),x,h/2-1,z);m.rotation.y=Math.random()*6}
// roads, curvy-ish network using segments
function road(x1,z1,x2,z2,w=9){const dx=x2-x1,dz=z2-z1,len=Math.hypot(dx,dz);const r=box(len,.18,w,0x252b30,(x1+x2)/2,.05,(z1+z2)/2);r.rotation.y=Math.atan2(dz,dx);roadMeshes.push(r);for(let t=0.08;t<.96;t+=.1){const px=x1+dx*t,pz=z1+dz*t;const line=box(.9,.05,.18,0xffd447,px,.16,pz);line.rotation.y=Math.atan2(dz,dx);roadMeshes.push(line)}}
road(-105,72,-55,38);road(-55,38,0,0);road(0,0,55,38);road(55,38,105,72);road(-80,-70,-42,-34);road(-42,-34,0,0);road(0,0,42,-34);road(42,-34,80,-70);road(-80,-70,-105,-10);road(-105,-10,-55,38);road(105,-10,55,38);road(105,-10,80,-70);road(-105,72,-105,-10);road(105,72,105,-10);road(-105,-10,105,-10,8);road(-105,72,105,72,8);
// center roundabout
cyl(18,.25,0x26343a,0,.18,0);cyl(10,.3,0x10202a,0,.34,0);cyl(5,.35,0x16dfff,0,.55,0,0x16dfff);cyl(2.2,6,0x1b9dca,0,3.4,0,0x19dfff);cyl(3.4,.2,0x16e7ff,0,6.5,0,0x16e7ff);
function tree(x,z,s=1){cyl(.65* s,4*s,0x6b4529,x,2*s,z);cyl(2.8*s,4*s,0x2c9b54,x,5*s,z);cyl(1.8*s,2.4*s,0x39b963,x,7*s,z)}
for(let i=0;i<90;i++){const a=Math.random()*Math.PI*2,r=28+Math.random()*100,x=Math.cos(a)*r,z=Math.sin(a)*r*.86;if(Math.abs(x)<18||Math.abs(z)<18)continue;tree(x,z,.7+Math.random()*.7)}
function building(id,name,x,z,c,desc){box(22,12,16,0x132232,x,6,z);box(24,.5,18,c,x,12.2,z,c);for(let i=-8;i<=8;i+=4)box(2,3,.2,0x6beaff,x+i,5,z-8.1,0x116b9b);for(let i=-8;i<=8;i+=4)box(2,3,.2,0x6beaff,x+i,9,z-8.1,0x116b9b);locations.push({id,name,x,z,desc,color:c});
 const sign=box(20,3,0.5,c,x,15,z-8.5,c);sign.userData.text=name;
}
building('about','ABOUT ME',-55,38,0x1b9cff,'Md Ihsan Ahmad — Designer, Developer and Creator. Explore the story, journey and vision behind the portfolio.');
building('skills','SKILLS',0,0,0xc72cff,'Graphic Design, Web Design, Photoshop, Illustrator, Canva and digital creative workflow.');
building('projects','PROJECTS',55,38,0x0877ff,'Selected projects: Freelancer Ihsan Website, Future Skills Academy and Osmani Karate Club.');
building('services','SERVICES',42,-34,0x8b36ff,'Web Design, Graphic Design, Branding, Social Media and Digital Solutions.');
building('contact','CONTACT',-42,-34,0x00d6c5,'Email, WhatsApp and social links — connect for your next project.');
// start garage
building('start','START',-80,-70,0xffa800,'Begin your journey here. Drive into the island and visit every portfolio zone.');
// billboards / character portrait
const tex=new THREE.TextureLoader().load('assets/ihsan-character.png');const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));sprite.position.set(-55,9,28);sprite.scale.set(10,15,1);world.add(sprite);
// sign labels as CSS-like sprites
function textSprite(t,x,y,z,color='#fff'){const c=document.createElement('canvas');c.width=1024;c.height=180;const q=c.getContext('2d');q.clearRect(0,0,1024,180);q.font='900 72px Orbitron';q.textAlign='center';q.fillStyle=color;q.shadowColor='#000';q.shadowBlur=18;q.fillText(t,512,105);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.position.set(x,y,z);s.scale.set(18,3.2,1);world.add(s)}
textSprite('MD IHSAN AHMAD',0,11,0,'#ffffff');textSprite('DREAM • DESIGN • BUILD',0,8,0,'#ffd21c');
// car
const car=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(3.5,.75,6.4),mat(0x0c1824,0x064d6d,.35));body.position.y=.9;body.castShadow=true;car.add(body);const hood=new THREE.Mesh(new THREE.BoxGeometry(3.1,.32,2.2),mat(0x152838,0x0b6b8a,.25));hood.position.set(0,1.35,-1.7);car.add(hood);const cabin=new THREE.Mesh(new THREE.BoxGeometry(2.7,.85,2.6),mat(0x0a2332,0x073d56,.15));cabin.position.set(0,1.5,.45);car.add(cabin);for(const x of [-1.75,1.75])for(const z of [-2,2]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.58,.58,.35,24),mat(0x050608));w.rotation.z=Math.PI/2;w.position.set(x,.55,z);car.add(w)}for(const x of [-1,1]){const l=new THREE.Mesh(new THREE.BoxGeometry(.55,.2,.1),mat(0x9ffaff,0x19e7ff),);l.position.set(x,1.05,-3.22);car.add(l)}car.position.set(-80,0,-70);car.rotation.y=Math.PI/4;scene.add(car);
// simple on-foot avatar (keeps recognizable color palette)
const player=new THREE.Group();const torso=box(1.5,2.2,1,0xf0f2f3,0,1.5,0);const head=cyl(.55,.8,0xc98d69,0,3.0,0,0);const cap=mesh(new THREE.CylinderGeometry(.6,.6,.18,20),mat(0x11151b),0,3.48,0);const legs=box(1.3,1.6,.9,0x171b20,0,.45,0);player.add(torso,head,cap,legs);player.position.copy(car.position);player.visible=false;scene.add(player);
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let inCar=true,running=false,near=null,speed=0;function toggleCar(){if(!running)return;inCar=!inCar;if(inCar){car.position.copy(player.position);player.visible=false;car.visible=true}else{player.position.copy(car.position).add(new THREE.Vector3(4,0,0).applyAxisAngle(new THREE.Vector3(0,1,0),car.rotation.y));player.visible=true;car.visible=false}}
document.getElementById('enter').onclick=()=>interact();document.getElementById('drive').onclick=toggleCar;document.getElementById('boost').onpointerdown=()=>keys[' ']=true;document.getElementById('boost').onpointerup=()=>keys[' ']=false;document.getElementById('jump').onclick=()=>{player.position.y=.8;setTimeout(()=>player.position.y=0,250)};
const joy=document.getElementById('joy'),stick=joy.querySelector('i');let ja=false;function jm(e){if(!ja)return;const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy)||1,m=Math.min(1,38/l);dx*=m;dy*=m;stick.style.transform=`translate(${dx}px,${dy}px)`;keys.w=dy<-12;keys.s=dy>12;keys.a=dx<-12;keys.d=dx>12}function je(){ja=false;stick.style.transform='translate(0,0)';keys.w=keys.s=keys.a=keys.d=false}joy.onpointerdown=e=>{ja=true;joy.setPointerCapture(e.pointerId);jm(e)};joy.onpointermove=jm;joy.onpointerup=je;joy.onpointercancel=je;
function panel(l){const body=document.getElementById('panelBody');let html=`<div class="tag">ZONE UNLOCKED</div><h2>${l.name}</h2><p>${l.desc}</p>`;if(l.id==='projects')html+=`<div class="cards"><div class="mini"><b>FREELANCER IHSAN</b><small>Personal freelance website.</small></div><div class="mini"><b>FUTURE SKILLS ACADEMY</b><small>Education & skills platform.</small></div><div class="mini"><b>OSMANI KARATE CLUB</b><small>Modern sports club website.</small></div></div>`;if(l.id==='skills')html+=`<div class="cards"><div class="mini"><b>PHOTOSHOP</b><small>Graphics & visual editing.</small></div><div class="mini"><b>ILLUSTRATOR</b><small>Vector & branding design.</small></div><div class="mini"><b>WEB DESIGN</b><small>Responsive modern websites.</small></div></div>`;if(l.id==='services')html+=`<div class="cards"><div class="mini"><b>WEB DESIGN</b><small>Landing pages & business sites.</small></div><div class="mini"><b>GRAPHIC DESIGN</b><small>Posters, social & branding.</small></div><div class="mini"><b>DIGITAL SOLUTIONS</b><small>Creative digital support.</small></div></div>`;if(l.id==='contact')html+=`<p><b>Email:</b> mdihsanahmad815@gmail.com</p><p><b>WhatsApp:</b> 01922889616</p>`;body.innerHTML=html;document.getElementById('panel').classList.remove('hidden')}
function interact(){if(near)panel(near)}document.getElementById('close').onclick=()=>document.getElementById('panel').classList.add('hidden');
function go(id){const l=locations.find(x=>x.id===id);if(!l)return;const target=new THREE.Vector3(l.x,0,l.z);if(inCar)car.position.set(l.x,0,l.z-10);else player.position.set(l.x,0,l.z-4);running=true;document.getElementById('startScreen').style.display='none'}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.getElementById('start').onclick=()=>{running=true;document.getElementById('startScreen').style.display='none'};document.getElementById('menu').onclick=()=>{running=false;document.getElementById('startScreen').style.display='grid'};
const map=document.getElementById('map'),ctx=map.getContext('2d');function drawMap(){ctx.fillStyle='#06131e';ctx.fillRect(0,0,190,190);ctx.strokeStyle='#233b47';ctx.lineWidth=10;ctx.strokeRect(8,8,174,174);ctx.strokeStyle='#586a71';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(15,95);ctx.lineTo(175,95);ctx.moveTo(95,15);ctx.lineTo(95,175);ctx.stroke();locations.forEach(l=>{let x=95+l.x*.7,y=95+l.z*.7;ctx.fillStyle=l.id==='start'?'#ffd21c':'#19e7ff';ctx.beginPath();ctx.arc(x,y,4,0,7);ctx.fill()});const p=inCar?car.position:player.position;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(95+p.x*.7,95+p.z*.7,5,0,7);ctx.fill()}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(running){const f=(keys.w?1:0)-(keys.s?1:0),turn=(keys.d?1:0)-(keys.a?1:0),boost=keys[' '];if(inCar){speed=THREE.MathUtils.lerp(speed,f*(boost?28:15),dt*5);car.rotation.y-=turn*1.9*dt*(Math.sign(speed)||1);car.translateZ(-speed*dt);car.position.x=THREE.MathUtils.clamp(car.position.x,-120,120);car.position.z=THREE.MathUtils.clamp(car.position.z,-105,105)}else{speed=THREE.MathUtils.lerp(speed,f*7,dt*6);player.rotation.y-=turn*2.4*dt;player.translateZ(-speed*dt)}}const obj=inCar?car:player;const behind=new THREE.Vector3(0,6.2,12).applyQuaternion(obj.quaternion).add(obj.position);camera.position.lerp(behind,1-Math.pow(.002,dt));const look=new THREE.Vector3(0,1.4,-2).applyQuaternion(obj.quaternion).add(obj.position);camera.lookAt(look);near=null;let bd=13;locations.forEach(l=>{const d=Math.hypot(obj.position.x-l.x,obj.position.z-l.z);if(d<bd){bd=d;near=l}});const h=document.getElementById('hint');h.style.opacity=near?'1':'0';h.innerHTML=near?`<b>${near.name}</b> · press <b>E</b> to enter`:'';document.getElementById('speed').textContent=Math.max(0,Math.round(Math.abs(speed)*5));document.getElementById('boostbar').style.setProperty('--boost',`${Math.min(100,Math.abs(speed)/28*100)}%`);drawMap();renderer.render(scene,camera)}animate();setTimeout(()=>{const l=document.getElementById('loading');l.style.opacity=0;setTimeout(()=>l.remove(),500)},900);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
